### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by avdaredevil** [Zevesh/timer-days#1]
You should leverage `gh-pages` to show off your element in a demo link. It gives insight onto your element and would increase adoption.

Just a suggestion ;)

Cheers.

**Comment by Zevesh** [comment]
I'll give it a try as soon as I can. I have recently started with GitHub (uploading code, I mean) and there is plenty to learn.

Thank you very much

**Comment by avdaredevil** [comment]
No worries, best of luck!
