### ISSUE TITLE
Support for Polymer 2

### ISSUE THREAD

**Issue by amanshu-kataria** [Zevesh/timer-days#7]
Timer-days doesn't work with Polymer 2 as the code needs to be upgraded to Polymer 2.
![image](https://user-images.githubusercontent.com/13014093/27229934-1cb7cb04-52cb-11e7-849f-b9650942e1e4.png)

**Comment by aacebes** [comment]
I'll try to fix it as soon as possible (no idea when it will be, though).
Thanks.

**Comment by amanshu-kataria** [comment]
@aacebes any good news regarding support for Polymer 2?

**Comment by aacebes** [comment]
@amanshu-kataria you can find the updated version in the new branch "Polymer2" (good name, I know). It isn't the very best code, but I hope it can help you.

Sorry for keep you waiting.
